###
GET http://localhost:3000

###
GET http://localhost:3000/partners

###
# @name createPartner
POST http://localhost:3000/partners
Content-Type: application/json

{
    "name": "Partner 1"
}

###
@partner_id = {{createPartner.response.body.$.id}}

###
GET http://localhost:3000/customers

###
# @name createCustomer
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 1",
    "cpf": "592.110.870-74"
}

###
@customer_id = {{createCustomer.response.body.$.id}}

###
# Cliente B: entra na lista de espera quando a seção esgota
# @name createCustomerB
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 2",
    "cpf": "703.758.870-91"
}

###
@customer_b_id = {{createCustomerB.response.body.$.id}}

###
GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Event 1",
    "description": "Description 1",
    "date": "2020-01-01T00:00:00.000Z",
    "partner_id": "{{partner_id}}"
}

###
@event_id = {{createEvent.response.body.$.id}}

###
GET http://localhost:3000/events/{{event_id}}/sections

###
# @name createSection
POST http://localhost:3000/events/{{event_id}}/sections
Content-Type: application/json

{
    "name": "Section 1",
    "description": "Description 1",
    "total_spots": 1,
    "price": 200
}

###
PUT http://localhost:3000/events/{{event_id}}/publish-all

###
@section_id = {{createSection.response.body.$.sections[0].id}}

###
PUT http://localhost:3000/events/{{event_id}}/sections/{{section_id}}
Content-Type: application/json

{
    "name": "Section 1 updateddddd",
    "description": "Description 1 updatedddd"
}

###
# @name listSpots
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots

###
@spot_id = {{listSpots.response.body.$[0].id}}

###
PUT http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots/{{spot_id}}
Content-Type: application/json

{
    "location": "Location 1 updateddddqqqq"
}

###
GET http://localhost:3000/events/{{event_id}}/orders

###
# Cliente A compra o único lugar da seção (a seção esgota)
# @name createOrder
POST http://localhost:3000/events/{{event_id}}/orders
Content-Type: application/json

{
    "customer_id": "{{customer_id}}",
    "section_id": "{{section_id}}",
    "spot_id": "{{spot_id}}",
    "card_token": "tok_visa"
}

###
@order_id = {{createOrder.response.body.$.id}}

###
# Lista de espera: cliente B entra na fila da seção esgotada (entrada PENDING)
POST http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/waiting-list
Content-Type: application/json

{
    "customer_id": "{{customer_b_id}}"
}

###
# Lista de espera: entradas na ordem de chegada, com seus status
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/waiting-list

###
# Cancelamento: OrderCancelled -> EventSpotReleased -> SpotOfferedToWaitingCustomer
POST http://localhost:3000/events/{{event_id}}/orders/{{order_id}}/cancel

###
# Consequência 1: o lugar voltou a ficar disponível ("reserved": false)
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots

###
# Consequência 2: a entrada do cliente B está NOTIFIED
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/waiting-list
